query SubBlocks @live(interval: 12000) {
  blockMetas(first: 200, orderBy: number, orderDirection: desc) {
    id
    number
    timestamp
    gas_used
    base_fee_per_gas
    hash
  }
}

query FetchBlocks {
  blockMetas(first: 200, orderBy: number, orderDirection: desc) {
    id
    number
    timestamp
    # gasUsed
    gas_used
    base_fee_per_gas
    hash
  }
}
