fragment FullBlock on Block {
    id
    number
    timestamp
    gasUsed
    baseFeePerGas
    txnCount
    minGasPrice
    maxGasPrice
    firstGasPrice
    lastGasPrice
    gasFees
    burnedFees
    minerTips
}

# query SubBlocks @live(interval: 12000) {
#   blocks(first: 200, orderBy: number, orderDirection: desc) {
#     ...FullBlock
#   }
# }
 
query FetchLastBlocks {
  blocks(first: 300, orderBy: timestamp, orderDirection: desc) {
    ...FullBlock
  }
}

query FetchBlocksSince($since: BigInt!) {
  blocks(first: 1000, orderBy: timestamp, where: { timestamp_gt: $since }) {
    ...FullBlock
  }
}

query FetchBlock($id: ID!) {
  block(id: $id) {
    ...FullBlock
  }
}

query FetchBlockByNumber($number: BigInt!) {
  blocks(where: { number: $number }) {
    ...FullBlock
  }
}

fragment FullTxn on Txn {
    id
    blockNumber
    index
    timestamp
    gasUsed
    gasPrice
    gasFee
    txnType
    maxPriorityFeePerGas
    burnedFee
    minerTip
}
 

query TxnsByBlock($number: BigInt!) {
  txns(first: 1000, orderBy: index, orderDirection: asc, where: { blockNumber: $number }) {
    ...FullTxn
  }
}

query Txn {
  txn(
    id: "0x7cc561e4f860fc33ccae5795562d65b988e02829f3be28d32345e53274e93b21"
  ) {
    ...FullTxn
  }
}
